### ISSUE TITLE
NPE on subproject mergeProduct1Flavor1JavaResource task when using DashO

### ISSUE THREAD

**Issue by fitillo** [gradle/android-cache-fix-gradle-plugin#108]
I'm having issues with a multi project build when using this plugin and DashO plugin at the same time in one subproject. My project is as follows:

- build.gradle
  - projectA (com.android.library) -> Subproject with NPE issue. DashO is only applied in this project. Dependency on projectB
  - projectB (com.android.library) -> Depencency on other (com.android.library) sub-projects
  - projects (com.android.library)
  - projectN (com.android.application) -> Dependency on projectA

These scenarios work (always with org.gradle.caching=true):
* Apply android-cache-fix-gradle-plugin as suggested in readme file (all subprojects). Disable dasho plugin on projectA
* Disable android-cache-fix-gradle-plugin for all projects and enable dasho plugin on projectA
* Apply dasho plugin on projectA and android-cache-fix-gradle-plugin for all projects except for projectA

Details:
* gradle version: 6.1.1
* com.android.tools.build:gradle:4.0.0
* DashO plugin: "com.preemptive.dasho:dasho-android:1.2.+". Installed DashO version: 10.3.0
* org.gradle.android.cache-fix plugin version: 1.0.7

Issue in org.gradle.android.workarounds.AbstractAbsolutePathWorkaround on line 28. Stacktrace:

```
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':projectA:mergeProduct1Flavor1ReleaseJavaResource'.
> java.lang.NullPointerException (no error message)
* Try:
Run with --debug option to get more log output. Run with --scan to get full insights.
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':projectA:mergeProduct1Flavor1ReleaseJavaResource'.
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:73)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:41)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:372)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:359)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:352)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:338)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:127)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:191)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:182)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
Caused by: java.lang.NullPointerException
	at org.gradle.api.internal.tasks.DefaultTaskInputs.unpackVarargs(DefaultTaskInputs.java:111)
	at org.gradle.api.internal.tasks.DefaultTaskInputs.access$100(DefaultTaskInputs.java:46)
	at org.gradle.api.internal.tasks.DefaultTaskInputs$1.call(DefaultTaskInputs.java:102)
	at org.gradle.api.internal.tasks.DefaultTaskInputs$1.call(DefaultTaskInputs.java:99)
	at org.gradle.util.GUtil.uncheckedCall(GUtil.java:425)
	at org.gradle.api.internal.tasks.TaskMutator.mutate(TaskMutator.java:45)
	at org.gradle.api.internal.tasks.DefaultTaskInputs.files(DefaultTaskInputs.java:99)
	at org.gradle.api.internal.tasks.DefaultTaskInputs.files(DefaultTaskInputs.java:45)
	at org.gradle.android.workarounds.AbstractAbsolutePathWorkaround$_apply_closure1$_closure2.doCall(AbstractAbsolutePathWorkaround.groovy:28)
	at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:41)
	at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:25)
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:42)
	at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:231)
	at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:150)
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:58)
	at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:325)
	at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:235)
	at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:141)
	at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:37)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy107.beforeExecute(Unknown Source)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:66)
	... 22 more
```

**Comment by runningcode** [comment]
Hey @fitillo, thanks for the detailed bug report. To investigate this further, do you happen to know where I can find the sources for the Dasho plugin? `com.preemptive.dasho:dasho-android:1.2.+`

**Comment by fitillo** [comment]
Sure, according to [official documentation](https://www.preemptive.com/dasho/pro/userguide/en/ref_dagp_config.html) repository is https://maven.preemptive.com. Don't know about sources though...

I'll give it a try with newer gradle and plugin versions.

**Comment by fitillo** [comment]
I think I've seen a potential problem.

Dasho forces to set minifyEnabled to true for the release build(s), to allow renaming and shrinking:

```
android {
     buildTypes {
         release {
             minifyEnabled true
         }
     }
 }
```
so it is enabled on our projectA (task failing belongs to this project).

According to [android cache documentation](https://developer.android.com/studio/build/build-cache), this disables caching of pre-dexed remote dependencies. So I don't know if it makes it incompatible with cache. Also, I haven't seen a way to enable caching but disable it for a particular subproject.

**Comment by fitillo** [comment]
Hi @runningcode, I can confirm the issue persists with gradle 6.5.1, fix plugin 1.0.8 and android plugin 4.0.1.

I've been investigating further though. Comparing apk without cache (our previous apk) and new generated apk with cache there's actually no difference. If I apply cache-fix-gradle-plugin though, there are some differences (minimal) in res/layout. My impression was that this plugin was needed for caching issues.

Could you please clarify?

**Comment by runningcode** [comment]
Hey @fitillo ,
This plugin fixes a number of caching issues. Right now, I would say almost all of the issues are cache misses with the remote build cache. You can see the list of workarounds as well as their related bugs filed against b.android.com here:
https://github.com/gradle/android-cache-fix-gradle-plugin/tree/master/src/main/groovy/org/gradle/android/workarounds

The specific issue with the NPE you are seeing is a fix for this remote cache miss: https://issuetracker.google.com/issues/140602655
You can see the code for that workaround here: https://github.com/gradle/android-cache-fix-gradle-plugin/blob/master/src/main/groovy/org/gradle/android/workarounds/MergeJavaResourcesWorkaround.groovy

**Comment by fitillo** [comment]
Hey @runningcode, thanks for clarifying. So if I understood properly, by not using this plugin, builds are not going to take full advantage of cache as there will be some cache misses but that's about it right? If that's the case I'll start by enabling cache and will maybe look into this further in the future.

Do you want me to close the issue or is it something you'd like investigating?

**Comment by runningcode** [comment]
Yes, as it currently stands that is correct. If you do not have the cache enabled there is no reason to use this plugin. Feel free to close the issue.

**Comment by fitillo** [comment]
Thanks!
