### ISSUE TITLE
org.gradle.internal.metaobject.AbstractDynamicObject$CustomMessageMissingMethodException: Could not find method copyExistingSchemasToTaskSpecificTmpDir()

### ISSUE THREAD

**Issue by vanniktech** [gradle/android-cache-fix-gradle-plugin#285]
Gradle: 7.4.2
AGP: 7.1.3
Cache Fix: 2.5.1

When running `gradle test` for an Android library I sometimes get:

```
Caused by: org.gradle.internal.metaobject.AbstractDynamicObject$CustomMessageMissingMethodException: Could not find method copyExistingSchemasToTaskSpecificTmpDir() for arguments [org.gradle.api.internal.file.DefaultFileOperations@3f21be39, property(org.gradle.api.file.Directory, undefined), property(org.gradle.api.file.Directory, fixed(class org.gradle.api.internal.file.DefaultFilePropertyFactory$FixedDirectory, /Users/niklas/dev/GitHub/vanniktech/feature/build/roomSchemas/compileDebugJavaWithJavac))] on task ':feature:compileDebugJavaWithJavac' of type org.gradle.api.tasks.compile.JavaCompile.
        at org.gradle.internal.metaobject.AbstractDynamicObject$CustomMissingMethodExecutionFailed.<init>(AbstractDynamicObject.java:190)
        at org.gradle.internal.metaobject.AbstractDynamicObject.methodMissingException(AbstractDynamicObject.java:184)
        at org.gradle.internal.metaobject.AbstractDynamicObject.invokeMethod(AbstractDynamicObject.java:167)
        at org.gradle.api.tasks.compile.JavaCompile_Decorated.invokeMethod(Unknown Source)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeOnDelegationObjects(ClosureMetaClass.java:408)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:350)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:61)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:203)
        at org.gradle.android.workarounds.RoomSchemaLocationWorkaround$_apply_closure2$_closure9$_closure12.doCall(RoomSchemaLocationWorkaround.groovy:122)
        at jdk.internal.reflect.GeneratedMethodAccessor7716.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
        at groovy.lang.Closure.call(Closure.java:412)
        at groovy.lang.Closure.call(Closure.java:428)
```

Note: I'm inside the android library directory. In my case it's called `feature` so the root build.gradle file is at `../build.gradle`.

When I execute `gradle feature:test` from the root directory it seems to be working fine.

**Comment by vanniktech** [comment]
This seems to be a regression from 2.5.0, if I downgrade I don't get that exception.

**Comment by ghale** [comment]
Yeah, this is some weird Groovy bug with `@CompileStatic` where sometimes it doesn't find static methods inside closures.  We can fix it on our side, though.  Thanks for reporting - we'll get it fixed shortly.
