### ISSUE TITLE
Cannot configure runtime classpath normalization after execution started.

### ISSUE THREAD

**Issue by vanniktech** [gradle/android-cache-fix-gradle-plugin#313]
I tried upgrading my project to Java 11 using:

```
  compileOptions {  
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
  }

  kotlinOptions {
    jvmTarget = JavaVersion.VERSION_11.toString()
  }
```

However when opening via IntelliJ 2022.2 EAP 5 or 6, I got this exception:

```
Caused by: org.gradle.api.GradleException: Cannot configure runtime classpath normalization after execution started.
	at org.gradle.normalization.internal.DefaultRuntimeClasspathNormalization$EvaluatableFilter.checkNotEvaluated(DefaultRuntimeClasspathNormalization.java:152)
	at org.gradle.normalization.internal.DefaultRuntimeClasspathNormalization$EvaluatableFilter.ignore(DefaultRuntimeClasspathNormalization.java:157)
	at org.gradle.normalization.internal.DefaultRuntimeClasspathNormalization$RuntimeMetaInfNormalization.ignoreAttribute(DefaultRuntimeClasspathNormalization.java:94)
	at org.gradle.normalization.MetaInfNormalization$ignoreAttribute.call(Unknown Source)
	at org.gradle.android.workarounds.JdkImageWorkaround$_applyRuntimeClasspathNormalization_closure4$_closure12$_closure13.doCall(JdkImageWorkaround.groovy:73)
	at jdk.internal.reflect.GeneratedMethodAccessor4532.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at groovy.lang.Closure.call(Closure.java:412)
	at groovy.lang.Closure.call(Closure.java:428)
	at org.gradle.util.internal.ClosureBackedAction.execute(ClosureBackedAction.java:72)
	at org.gradle.util.internal.ConfigureUtil.configureTarget(ConfigureUtil.java:155)
	at org.gradle.util.internal.ConfigureUtil.configure(ConfigureUtil.java:106)
	at org.gradle.util.internal.ConfigureUtil$WrappedConfigureAction.execute(ConfigureUtil.java:167)
	at org.gradle.normalization.internal.DefaultRuntimeClasspathNormalization.metaInf(DefaultRuntimeClasspathNormalization.java:53)
	at org.gradle.normalization.internal.DefaultRuntimeClasspathNormalization_Decorated.metaInf(Unknown Source)
	at org.gradle.normalization.internal.DefaultRuntimeClasspathNormalization_Decorated$metaInf.call(Unknown Source)
	at org.gradle.android.workarounds.JdkImageWorkaround$_applyRuntimeClasspathNormalization_closure4$_closure12.doCall(JdkImageWorkaround.groovy:72)
	at jdk.internal.reflect.GeneratedMethodAccessor4531.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at groovy.lang.Closure.call(Closure.java:412)
	at groovy.lang.Closure.call(Closure.java:428)
	at org.gradle.util.internal.ClosureBackedAction.execute(ClosureBackedAction.java:72)
	at org.gradle.util.internal.ConfigureUtil.configureTarget(ConfigureUtil.java:155)
	at org.gradle.util.internal.ConfigureUtil.configure(ConfigureUtil.java:106)
	at org.gradle.util.internal.ConfigureUtil$WrappedConfigureAction.execute(ConfigureUtil.java:167)
	at org.gradle.normalization.internal.DefaultInputNormalizationHandler.runtimeClasspath(DefaultInputNormalizationHandler.java:36)
	at org.gradle.normalization.internal.DefaultInputNormalizationHandler_Decorated.runtimeClasspath(Unknown Source)
	at org.gradle.normalization.internal.DefaultInputNormalizationHandler_Decorated$runtimeClasspath.call(Unknown Source)
	at org.gradle.android.workarounds.JdkImageWorkaround$_applyRuntimeClasspathNormalization_closure4.doCall(JdkImageWorkaround.groovy:71)
```

I'm pretty sure I was using the latest [2.5.5](https://github.com/gradle/android-cache-fix-gradle-plugin/releases/tag/v2.5.5) which had a fix for this workaround but it seems to be a different one.

**Comment by ghale** [comment]
There is definitely something odd going on here, although I suspect it's any issue somewhere else that is simply being surfaced by this workaround.  It implies the android plugin is getting applied weirdly (e.g. applied twice or applied late or something like that).  Can you share the rest of the stack trace?

**Comment by vanniktech** [comment]
Thanks! I can test this out once a new version has been published

**Comment by ghale** [comment]
This is in release 2.5.6.  Let us know if you are still having any issues.
