### ISSUE TITLE
Android Gradle Plugin 7.4.0-beta02 fails with android-cache-fix-gradle-plugin

### ISSUE THREAD

**Issue by ganadist** [gradle/android-cache-fix-gradle-plugin#353]
Environment :
  Gradle : 7.5.1
  AGP : 7.4.0-beta02
  android-cache-fix-gradle-plugin : 2.5.6
  Java : OpenJDK 11

How to reproduce failure
```
git clone https://github.com/ganadist/VersionCodeDemo -b agp74_cache_fix
cd VersionCodeDemo
./gradlew :lib:glide:assemble

> Configure project :lib:glide
WARNING: Android plugin 7.4.0-beta02 has not been tested with this version of the Android cache fix plugin, although it may work.  We test against only the latest patch release versions of Android Gradle plugin: 7.0.4, 7.1.3, 7.2.1, 7.3.0-beta05, 7.4.0-alpha08.  If 7.4.0-beta02 is newly released, we may not have had a chance to release a version tested against it yet.  Proceed with caution.  You can suppress this warning with with -Dorg.gradle.android.cache-fix.ignoreVersionCheck=true.
Values of variant API AnnotationProcessorOptions.arguments are queried and may return non final values, this is unsupported

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':lib:glide'.
> com.android.build.gradle.internal.crash.ExternalApiUsageException: com.android.build.gradle.internal.dsl.AgpDslLockedException: It is too late to modify AnnotationProcessor::argumentProviders
  It has already been read to configure this project.
  Consider either moving this call to be during evaluation,
  or using the variant API.


Caused by: com.android.build.gradle.internal.dsl.AgpDslLockedException: It is too late to modify AnnotationProcessor::argumentProviders	
It has already been read to configure this project.	
Consider either moving this call to be during evaluation,	
or using the variant API.	
	at com.android.build.gradle.internal.dsl.decorator.LockableList.add(LockableList.kt:83)	
		•••
	at org.gradle.android.workarounds.RoomSchemaLocationWorkaround$_apply_closure3$_closure14.doCall(RoomSchemaLocationWorkaround.groovy:137)	
		•••
	at com.android.build.gradle.LibraryExtension.addVariant(LibraryExtension.kt:102)	
	at com.android.build.gradle.internal.ApiObjectFactory.create(ApiObjectFactory.java:119)	
	at com.android.build.gradle.internal.plugins.BasePlugin.createAndroidTasks(BasePlugin.kt:706)	
	at com.android.build.gradle.internal.plugins.BasePlugin$createTasks$2$1.call(BasePlugin.kt:572)	
	at com.android.build.gradle.internal.profile.NoOpAnalyticsConfiguratorService.recordBlock(NoOpAnalyticsConfiguratorService.kt:53)	
	at com.android.build.gradle.internal.plugins.BasePlugin$createTasks$2.accept(BasePlugin.kt:567)	
	at com.android.build.gradle.internal.plugins.BasePlugin$createTasks$2.accept(BasePlugin.kt:564)	
	at com.android.build.gradle.internal.crash.CrashReporting$afterEvaluate$1.execute(crash_reporting.kt:37)	
	at com.android.build.gradle.internal.crash.CrashReporting$afterEvaluate$1.execute(crash_reporting.kt:35)
```

**Comment by ghale** [comment]
Thanks for reporting this.  In your `gradle/project_base.gradle` script, you can workaround the issue by replacing `tasks.withType(JavaCompile) { ... }` with `tasks.withType(JavaCompile).configureEach { ... }` (see [here](https://docs.gradle.org/current/userguide/task_configuration_avoidance.html) for some discussion of eager vs lazy task configuration).  The `tasks.withType(JavaCompile) { ... }` is causing all previously registered tasks to be eagerly created, which is then causing the argument processor lists to be locked early, which then leads to this error when the Room workaround configuration is applied via the old variant api.  I suspect changing the Room workaround to use the new variant api would also fix this, but making that change could be tricky because not everything is available in all of the AGP versions supported by the android cache fix plugin.  It's something that we'll explore, though.  In the meantime, eagerly creating tasks like this is an anti-pattern anyways, so changing to use `configureEach` would also eliminate a bad practice.
