### ISSUE TITLE
Issue with AGP 7.4.0

### ISSUE THREAD

**Issue by eboudrant** [gradle/android-cache-fix-gradle-plugin#412]
Hello, I'm trying AGP 7.4.0 using latest version and it fails to apply the plugin : 

```
Caused by: java.lang.NullPointerException: Cannot invoke method selector() on null object
	at org.gradle.android.workarounds.RoomSchemaLocationWorkaround.applyToAllAndroidVariantsWithNewVariantApi(RoomSchemaLocationWorkaround.groovy:277)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.gradle.android.workarounds.RoomSchemaLocationWorkaround.applyToAllAndroidVariants(RoomSchemaLocationWorkaround.groovy:257)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.gradle.android.workarounds.RoomSchemaLocationWorkaround.apply(RoomSchemaLocationWorkaround.groovy:81)
	at org.gradle.android.AndroidCacheFixPlugin$_apply_closure1.doCall(AndroidCacheFixPlugin.groovy:69)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.gradle.android.AndroidCacheFixPlugin.apply(AndroidCacheFixPlugin.groovy:67)
	at org.gradle.android.AndroidCacheFixPlugin.apply(AndroidCacheFixPlugin.groovy)
	at org.gradle.api.internal.plugins.ImperativeOnlyPluginTarget.applyImperative(ImperativeOnlyPluginTarget.java:43)
```

Gradle : 7.5
AGP : 7.4.0
Kotlin 1.7.20
Cache fix plugin : 2.6.1

**Comment by cdsap** [comment]
hi @eboudrant, thanks for the issue. Fixed in #414 and released a new version `2.6.2`
Closing this issue
