### ISSUE TITLE
Cannot query the value of property 'arguments'

### ISSUE THREAD

**Issue by changusmc** [gradle/android-cache-fix-gradle-plugin#541]
Gradle 7.4.1 
AGP 7.3.0

It seems that after updating com.android.tools:sdk-common from 27.2.0 to 31.0.2, we're hitting this issue when trying to build our app.

```
> Configure project :app

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.

Caused by: java.lang.IllegalStateException: Cannot query the value of property 'arguments' because configuration of project ':app' has not completed yet.
        at org.gradle.api.internal.provider.AbstractProperty$NonFinalizedValue.maybeFinalizeOnRead(AbstractProperty.java:368)
        at org.gradle.api.internal.provider.AbstractProperty.beforeRead(AbstractProperty.java:229)
        at org.gradle.api.internal.provider.AbstractProperty.beforeRead(AbstractProperty.java:225)
        at org.gradle.api.internal.provider.DefaultMapProperty$KeySetProvider.calculateOwnValue(DefaultMapProperty.java:294)
        at org.gradle.api.internal.provider.AbstractMinimalProvider.get(AbstractMinimalProvider.java:84)
        at org.gradle.api.provider.Provider$get$1.call(Unknown Source)
        at org.gradle.android.workarounds.room.JavaCompileWorkaround$1$_getNewVariantConfiguration_closure2.doCall(JavaCompileWorkaround.groovy:63)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at org.gradle.util.internal.ClosureBackedAction.execute(ClosureBackedAction.java:72)
        at org.gradle.util.internal.ConfigureUtil.configureTarget(ConfigureUtil.java:155)
        at org.gradle.util.internal.ConfigureUtil.configure(ConfigureUtil.java:106)
        at org.gradle.util.internal.ConfigureUtil$WrappedConfigureAction.execute(ConfigureUtil.java:167)
        at com.android.build.api.extension.impl.OperationsRegistrar.executeOperations(OperationsRegistrar.kt:66)
        at com.android.build.gradle.internal.VariantManager.createVariantsFromCombination(VariantManager.kt:993)
        at com.android.build.gradle.internal.VariantManager.computeVariants(VariantManager.kt:235)
        at com.android.build.gradle.internal.VariantManager.createVariants(VariantManager.kt:193)
        at com.android.build.gradle.internal.plugins.BasePlugin.createAndroidTasks(BasePlugin.kt:681)
        at com.android.build.gradle.internal.plugins.BasePlugin$createTasks$2$1.call(BasePlugin.kt:575)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:69)
```

**Comment by changusmc** [comment]
Seems to have been fixed by migrating to Gradle 8.0 and AGP 8.0.
