### ISSUE TITLE
AGP 4.2 incompatibility

### ISSUE THREAD

**Issue by ZacSweers** [gradle/android-cache-fix-gradle-plugin#99]
Tested with 4.2.0-alpha04

```
Caused by: java.lang.NullPointerException: Cannot invoke method setAccessible() on null object
	at org.gradle.android.workarounds.MergeJavaResourcesWorkaround.setPropertyValue(MergeJavaResourcesWorkaround.groovy:22)
	at org.gradle.android.workarounds.AbstractAbsolutePathWorkaround$_apply_closure1$_closure2.doCall(AbstractAbsolutePathWorkaround.groovy:27)
```

**Comment by runningcode** [comment]
Thanks for reporting. I assume you had `org.gradle.android.cache-fix.ignoreVersionCheck=true` set?
Even with that set, the code shouldn't be applying the workaround since it was fixed in a lower version. I wonder if there is some bug in the version checking logic.

Looks like this was changed from 
AGP 4.0
```
    @get:InputFiles
    @get:PathSensitive(PathSensitivity.ABSOLUTE)
    @get:Optional
    var projectJavaRes: FileCollection? = null
        private set
```
AGP 4.1.0 and AGP 4.2.0
```
    @get:InputFiles
    @get:PathSensitive(PathSensitivity.RELATIVE)
    @get:Optional
    abstract val projectJavaRes: ConfigurableFileCollection
```

**Comment by ZacSweers** [comment]
Confirmed ignoreVersionCheck is set to true
